// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actions": {
            "post": {
                "description": "Perform a domain-specific action",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Perform an action",
                "parameters": [
                    {
                        "description": "Action request",
                        "name": "action",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ActionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fx/history": {
            "get": {
                "description": "Get daily FX rates for a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fx"
                ],
                "summary": "Get FX history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base currency (default USD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Quote currency (default VND)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fx/today": {
            "get": {
                "description": "Fetch today's FX rate for a currency pair, cache it, and return",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fx"
                ],
                "summary": "Get today's FX rate (fetched and stored)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base currency (default USD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Quote currency (default VND)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/investments": {
            "get": {
                "description": "Retrieve investments based on filter criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Get investments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by asset",
                        "name": "asset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by account",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by horizon",
                        "name": "horizon",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by open status",
                        "name": "is_open",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset results",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Investment"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/investments/available": {
            "get": {
                "description": "Retrieve open investments available for stake operations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Get available investments for stake",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset",
                        "name": "asset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account",
                        "name": "account",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Horizon",
                        "name": "horizon",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Investment"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/investments/stake": {
            "post": {
                "description": "Process a stake transaction and create/update investment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Create stake investment",
                "parameters": [
                    {
                        "description": "Stake transaction",
                        "name": "stake",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Investment"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/investments/summary": {
            "get": {
                "description": "Retrieve investment summary statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Get investment summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by asset",
                        "name": "asset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by account",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by horizon",
                        "name": "horizon",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by open status",
                        "name": "is_open",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.InvestmentSummary"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/investments/unstake": {
            "post": {
                "description": "Process an unstake transaction and update investment. The field ` + "`" + `investment_id` + "`" + ` is required and must reference an existing open investment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Create unstake investment",
                "parameters": [
                    {
                        "description": "Unstake transaction (requires investment_id)",
                        "name": "unstake",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Investment"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/investments/{id}": {
            "get": {
                "description": "Retrieve a specific investment by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "investments"
                ],
                "summary": "Get investment by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Investment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Investment"
                        }
                    },
                    "404": {
                        "description": "Investment not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/prices/daily": {
            "get": {
                "description": "Get daily prices for a symbol or asset ID in a currency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Get daily asset prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset symbol (e.g., BTC)",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "asset_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target currency (default USD)",
                        "name": "currency",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/borrows/outstanding": {
            "get": {
                "description": "Get list of outstanding borrows as of a date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get outstanding borrows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "As of date (YYYY-MM-DD)",
                        "name": "as_of",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OutstandingBorrow"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/cashflow": {
            "get": {
                "description": "Get cash flow over a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get cash flow report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Days back from end_date",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CashFlowReport"
                        }
                    },
                    "400": {
                        "description": "Invalid period parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/expected-borrow-outflows": {
            "get": {
                "description": "Project remaining principal and interest for active borrows as of a date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get expected borrow outflows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "As-of date (YYYY-MM-DD)",
                        "name": "as_of",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OutflowProjection"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/holdings": {
            "get": {
                "description": "Get current holdings as of a date with portfolio percentages",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get holdings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "As of date (YYYY-MM-DD)",
                        "name": "as_of",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Holding"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/holdings/summary": {
            "get": {
                "description": "Get aggregated holdings summary as of a date with portfolio percentages",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get holdings summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "As of date (YYYY-MM-DD)",
                        "name": "as_of",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HoldingSummary"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/pnl": {
            "get": {
                "description": "Get profit and loss over a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get PnL report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Days back from end_date",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PnLReport"
                        }
                    },
                    "400": {
                        "description": "Invalid period parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/spending": {
            "get": {
                "description": "Get spending over a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get spending report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Days back from end_date",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SpendingReport"
                        }
                    },
                    "400": {
                        "description": "Invalid period parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "description": "Get a list of transactions or create a new one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List or create transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated transaction types",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated asset symbols",
                        "name": "assets",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated account names",
                        "name": "accounts",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated tag names",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Counterparty name",
                        "name": "counterparty",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target currencies for FX conversion (comma-separated), defaults to USD,VND",
                        "name": "currencies",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Basic transactions without FX conversion",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaction"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Get a list of transactions or create a new one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List or create transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated transaction types",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated asset symbols",
                        "name": "assets",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated account names",
                        "name": "accounts",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated tag names",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Counterparty name",
                        "name": "counterparty",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target currencies for FX conversion (comma-separated), defaults to USD,VND",
                        "name": "currencies",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Basic transactions without FX conversion",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaction"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "description": "Operate on a single transaction by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get, update, or delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Operate on a single transaction by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get, update, or delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Operate on a single transaction by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get, update, or delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/{vaultId}/assets/{asset}/holdings": {
            "get": {
                "description": "Get derived holdings for a specific asset/account within a vault",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Get asset holdings in a vault (derived)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vaultId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset symbol",
                        "name": "asset",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "account",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/{vaultId}/holdings": {
            "get": {
                "description": "Get derived vault holdings from transaction ledger",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Get vault holdings (derived)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vaultId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/{vaultId}/transactions": {
            "get": {
                "description": "List transactions for a vault (supports limit, offset, type, status)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List vault transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vaultId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transaction type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.VaultTransaction"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new transaction recorded in the vault ledger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Create a vault transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vaultId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vault transaction payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VaultTransaction"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.VaultTransaction"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/{vaultId}/user/{userId}/holdings": {
            "get": {
                "description": "Get derived user holdings in a vault from transaction ledger",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Get user holdings (derived)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vaultId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/{vaultId}/user/{userId}/transactions": {
            "get": {
                "description": "List transactions for a user in a vault (supports limit, offset)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List user transactions in a vault",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vaultId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.VaultTransaction"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AccountPnL": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "realized_pnl_usd": {
                    "type": "number"
                },
                "realized_pnl_vnd": {
                    "type": "number"
                },
                "total_pnl_usd": {
                    "type": "number"
                },
                "total_pnl_vnd": {
                    "type": "number"
                },
                "total_value_usd": {
                    "type": "number"
                },
                "total_value_vnd": {
                    "type": "number"
                }
            }
        },
        "models.ActionRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "models.ActionResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "executed_at": {
                    "type": "string"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Transaction"
                    }
                }
            }
        },
        "models.AssetPnL": {
            "type": "object",
            "properties": {
                "asset": {
                    "type": "string"
                },
                "average_cost_usd": {
                    "type": "number"
                },
                "current_quantity": {
                    "type": "number"
                },
                "current_value_usd": {
                    "type": "number"
                },
                "current_value_vnd": {
                    "type": "number"
                },
                "realized_pnl_usd": {
                    "type": "number"
                },
                "realized_pnl_vnd": {
                    "type": "number"
                },
                "total_pnl_usd": {
                    "type": "number"
                },
                "total_pnl_vnd": {
                    "type": "number"
                }
            }
        },
        "models.CashFlowByType": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "inflow_usd": {
                    "type": "number"
                },
                "inflow_vnd": {
                    "type": "number"
                },
                "net_usd": {
                    "type": "number"
                },
                "net_vnd": {
                    "type": "number"
                },
                "outflow_usd": {
                    "type": "number"
                },
                "outflow_vnd": {
                    "type": "number"
                }
            }
        },
        "models.CashFlowReport": {
            "type": "object",
            "properties": {
                "by_tag": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.CashFlowByType"
                    }
                },
                "by_type": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.CashFlowByType"
                    }
                },
                "combined_in_usd": {
                    "description": "Combined totals = Operating + Financing",
                    "type": "number"
                },
                "combined_in_vnd": {
                    "type": "number"
                },
                "combined_net_usd": {
                    "type": "number"
                },
                "combined_net_vnd": {
                    "type": "number"
                },
                "combined_out_usd": {
                    "type": "number"
                },
                "combined_out_vnd": {
                    "type": "number"
                },
                "financing_in_usd": {
                    "description": "Financing totals include borrow (as inflow), repay_borrow and interest_expense (as outflows)",
                    "type": "number"
                },
                "financing_in_vnd": {
                    "type": "number"
                },
                "financing_net_usd": {
                    "type": "number"
                },
                "financing_net_vnd": {
                    "type": "number"
                },
                "financing_out_usd": {
                    "type": "number"
                },
                "financing_out_vnd": {
                    "type": "number"
                },
                "net_usd": {
                    "type": "number"
                },
                "net_vnd": {
                    "type": "number"
                },
                "operating_in_usd": {
                    "description": "Operating totals exclude financing flows (borrow, repay_borrow, interest_expense)",
                    "type": "number"
                },
                "operating_in_vnd": {
                    "type": "number"
                },
                "operating_net_usd": {
                    "type": "number"
                },
                "operating_net_vnd": {
                    "type": "number"
                },
                "operating_out_usd": {
                    "type": "number"
                },
                "operating_out_vnd": {
                    "type": "number"
                },
                "period": {
                    "$ref": "#/definitions/models.Period"
                },
                "total_in_usd": {
                    "type": "number"
                },
                "total_in_vnd": {
                    "type": "number"
                },
                "total_out_usd": {
                    "type": "number"
                },
                "total_out_vnd": {
                    "type": "number"
                }
            }
        },
        "models.CostBasisMethod": {
            "type": "string",
            "enum": [
                "fifo",
                "lifo",
                "average"
            ],
            "x-enum-varnames": [
                "CostBasisFIFO",
                "CostBasisLIFO",
                "CostBasisAverage"
            ]
        },
        "models.Holding": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "asset": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_vault": {
                    "type": "boolean"
                },
                "last_updated": {
                    "type": "string"
                },
                "percentage": {
                    "description": "Percentage of total portfolio value",
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "value_usd": {
                    "type": "number"
                },
                "value_vnd": {
                    "type": "number"
                }
            }
        },
        "models.HoldingSummary": {
            "type": "object",
            "properties": {
                "by_account": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.Holding"
                        }
                    }
                },
                "by_asset": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.Holding"
                    }
                },
                "last_updated": {
                    "type": "string"
                },
                "total_value_usd": {
                    "type": "number"
                },
                "total_value_vnd": {
                    "type": "number"
                }
            }
        },
        "models.Investment": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "asset": {
                    "type": "string"
                },
                "cost_basis_method": {
                    "description": "Configuration",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.CostBasisMethod"
                        }
                    ]
                },
                "created_at": {
                    "description": "Metadata",
                    "type": "string"
                },
                "deposit_cost": {
                    "description": "Total cost in USD",
                    "type": "number"
                },
                "deposit_date": {
                    "description": "Aggregated deposit information",
                    "type": "string"
                },
                "deposit_qty": {
                    "description": "Total quantity deposited",
                    "type": "number"
                },
                "deposit_unit_cost": {
                    "description": "Weighted average unit cost",
                    "type": "number"
                },
                "horizon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_migrated": {
                    "type": "boolean"
                },
                "is_open": {
                    "description": "Status and quantities",
                    "type": "boolean"
                },
                "pnl": {
                    "description": "P\u0026L calculation",
                    "type": "number"
                },
                "pnl_percent": {
                    "type": "number"
                },
                "realized_pnl": {
                    "description": "Derived fields (not persisted)",
                    "type": "number"
                },
                "remaining_qty": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "vault_id": {
                    "description": "Vault migration fields",
                    "type": "string"
                },
                "withdrawal_date": {
                    "description": "Withdrawal information (if closed)",
                    "type": "string"
                },
                "withdrawal_qty": {
                    "type": "number"
                },
                "withdrawal_unit_price": {
                    "type": "number"
                },
                "withdrawal_value": {
                    "type": "number"
                }
            }
        },
        "models.InvestmentSummary": {
            "type": "object",
            "properties": {
                "closed_investments": {
                    "type": "integer"
                },
                "open_investments": {
                    "type": "integer"
                },
                "open_market_value": {
                    "type": "number"
                },
                "realized_pnl": {
                    "type": "number"
                },
                "roi_percent": {
                    "type": "number"
                },
                "total_deposits": {
                    "type": "number"
                },
                "total_investments": {
                    "type": "integer"
                },
                "total_pnl": {
                    "type": "number"
                },
                "total_withdrawals": {
                    "type": "number"
                },
                "unrealized_pnl": {
                    "type": "number"
                }
            }
        },
        "models.OutflowProjection": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "as_of": {
                    "type": "string"
                },
                "asset": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interest_accrued": {
                    "type": "number"
                },
                "remaining_principal": {
                    "type": "number"
                },
                "total_outflow": {
                    "type": "number"
                }
            }
        },
        "models.OutstandingBorrow": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                }
            }
        },
        "models.Period": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "models.PnLReport": {
            "type": "object",
            "properties": {
                "by_account": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.AccountPnL"
                    }
                },
                "by_asset": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.AssetPnL"
                    }
                },
                "period": {
                    "$ref": "#/definitions/models.Period"
                },
                "realized_pnl_usd": {
                    "type": "number"
                },
                "realized_pnl_vnd": {
                    "type": "number"
                },
                "roi_percent": {
                    "type": "number"
                },
                "total_pnl_usd": {
                    "type": "number"
                },
                "total_pnl_vnd": {
                    "type": "number"
                }
            }
        },
        "models.SpendingByDay": {
            "type": "object",
            "properties": {
                "amount_usd": {
                    "type": "number"
                },
                "amount_vnd": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "models.SpendingByTag": {
            "type": "object",
            "properties": {
                "amount_usd": {
                    "type": "number"
                },
                "amount_vnd": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                }
            }
        },
        "models.SpendingReport": {
            "type": "object",
            "properties": {
                "by_counterparty": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.SpendingByTag"
                    }
                },
                "by_day": {
                    "description": "Daily breakdown of spending (outflows only) keyed by YYYY-MM-DD",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.SpendingByDay"
                    }
                },
                "by_tag": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.SpendingByTag"
                    }
                },
                "period": {
                    "$ref": "#/definitions/models.Period"
                },
                "top_expenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TransactionSummary"
                    }
                },
                "total_usd": {
                    "type": "number"
                },
                "total_vnd": {
                    "type": "number"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount_local": {
                    "description": "Amount fields",
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "borrow_active": {
                    "type": "boolean"
                },
                "borrow_apr": {
                    "description": "Borrow metadata (for type = 'borrow')",
                    "type": "number"
                },
                "borrow_term_days": {
                    "type": "integer"
                },
                "cashflow_local": {
                    "type": "number"
                },
                "counterparty": {
                    "type": "string"
                },
                "created_at": {
                    "description": "Audit fields",
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "delta_qty": {
                    "description": "Derived metrics",
                    "type": "number"
                },
                "entry_date": {
                    "type": "string"
                },
                "exit_date": {
                    "type": "string"
                },
                "fee_local": {
                    "description": "Fees (stored in local currency, will be converted dynamically)",
                    "type": "number"
                },
                "horizon": {
                    "description": "Optional tracking",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "internal_flow": {
                    "description": "Flow flags",
                    "type": "boolean"
                },
                "investment_id": {
                    "description": "Enhanced investment tracking - links transaction to investment position",
                    "type": "string"
                },
                "local_currency": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "price_local": {
                    "type": "number"
                },
                "quantity": {
                    "description": "Amount fields",
                    "type": "number"
                },
                "tag": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.TransactionSummary": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount_usd": {
                    "type": "number"
                },
                "amount_vnd": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "counterparty": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.TransactionWithFX": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount_local": {
                    "description": "Amount fields",
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "borrow_active": {
                    "type": "boolean"
                },
                "borrow_apr": {
                    "description": "Borrow metadata (for type = 'borrow')",
                    "type": "number"
                },
                "borrow_term_days": {
                    "type": "integer"
                },
                "cashflow_local": {
                    "type": "number"
                },
                "counterparty": {
                    "type": "string"
                },
                "created_at": {
                    "description": "Audit fields",
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "delta_qty": {
                    "description": "Derived metrics",
                    "type": "number"
                },
                "entry_date": {
                    "type": "string"
                },
                "exit_date": {
                    "type": "string"
                },
                "fee_local": {
                    "description": "Fees (stored in local currency, will be converted dynamically)",
                    "type": "number"
                },
                "fx_rates": {
                    "description": "Map of currency pairs to rates, e.g., \"USD-VND\": 24000",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "horizon": {
                    "description": "Optional tracking",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "internal_flow": {
                    "description": "Flow flags",
                    "type": "boolean"
                },
                "investment_id": {
                    "description": "Enhanced investment tracking - links transaction to investment position",
                    "type": "string"
                },
                "local_currency": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "price_local": {
                    "type": "number"
                },
                "quantity": {
                    "description": "Amount fields",
                    "type": "number"
                },
                "tag": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.VaultTransaction": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount_usd": {
                    "description": "Financial amounts",
                    "type": "number"
                },
                "asset": {
                    "description": "Asset information (for rebalancing and asset-specific transactions)",
                    "type": "string"
                },
                "asset_price": {
                    "type": "number"
                },
                "asset_quantity": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "description": "Audit fields",
                    "type": "string"
                },
                "executed_at": {
                    "type": "string"
                },
                "external_tx_id": {
                    "type": "string"
                },
                "fee_amount": {
                    "description": "Fee information",
                    "type": "number"
                },
                "fee_rate": {
                    "type": "number"
                },
                "fee_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "price_per_share": {
                    "type": "number"
                },
                "share_price_after": {
                    "type": "number"
                },
                "share_price_before": {
                    "type": "number"
                },
                "shares": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "Metadata",
                    "type": "string"
                },
                "transaction_hash": {
                    "type": "string"
                },
                "type": {
                    "description": "Transaction details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.VaultTransactionType"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_shares_after": {
                    "type": "number"
                },
                "user_shares_before": {
                    "description": "User balance snapshots",
                    "type": "number"
                },
                "vault_aum_after": {
                    "type": "number"
                },
                "vault_aum_before": {
                    "description": "Price and valuation information",
                    "type": "number"
                },
                "vault_id": {
                    "type": "string"
                }
            }
        },
        "models.VaultTransactionType": {
            "type": "string",
            "enum": [
                "deposit",
                "withdrawal",
                "mint_shares",
                "burn_shares",
                "rebalance",
                "fee",
                "yield",
                "income",
                "expense",
                "valuation"
            ],
            "x-enum-varnames": [
                "VaultTxTypeDeposit",
                "VaultTxTypeWithdrawal",
                "VaultTxTypeMintShares",
                "VaultTxTypeBurnShares",
                "VaultTxTypeRebalance",
                "VaultTxTypeFee",
                "VaultTxTypeYield",
                "VaultTxTypeIncome",
                "VaultTxTypeExpense",
                "VaultTxTypeValuation"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Nami Backend API",
	Description:      "API documentation for Nami Transaction Tracking System.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
