// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actions": {
            "post": {
                "description": "Perform a domain-specific action",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Perform an action",
                "parameters": [
                    {
                        "description": "Action request",
                        "name": "action",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.ActionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.ActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fx/history": {
            "get": {
                "description": "Get daily FX rates for a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fx"
                ],
                "summary": "Get FX history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base currency (default USD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Quote currency (default VND)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fx/today": {
            "get": {
                "description": "Fetch today's FX rate for a currency pair, cache it, and return",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fx"
                ],
                "summary": "Get today's FX rate (fetched and stored)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base currency (default USD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Quote currency (default VND)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/prices/daily": {
            "get": {
                "description": "Get daily prices for a symbol or asset ID in a currency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Get daily asset prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset symbol (e.g., BTC)",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "asset_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target currency (default USD)",
                        "name": "currency",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/borrows/outstanding": {
            "get": {
                "description": "Get list of outstanding borrows as of a date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get outstanding borrows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "As of date (YYYY-MM-DD)",
                        "name": "as_of",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.OutstandingBorrow"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/cashflow": {
            "get": {
                "description": "Get cash flow over a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get cash flow report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Days back from end_date",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.CashFlowReport"
                        }
                    },
                    "400": {
                        "description": "Invalid period parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/holdings": {
            "get": {
                "description": "Get current holdings as of a date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get holdings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "As of date (YYYY-MM-DD)",
                        "name": "as_of",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Holding"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/holdings/summary": {
            "get": {
                "description": "Get aggregated holdings summary as of a date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get holdings summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "As of date (YYYY-MM-DD)",
                        "name": "as_of",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.HoldingSummary"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/pnl": {
            "get": {
                "description": "Get profit and loss over a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get PnL report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Days back from end_date",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.PnLReport"
                        }
                    },
                    "400": {
                        "description": "Invalid period parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reports/spending": {
            "get": {
                "description": "Get spending over a period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get spending report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Days back from end_date",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.SpendingReport"
                        }
                    },
                    "400": {
                        "description": "Invalid period parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "description": "Get a list of transactions or create a new one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List or create transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated transaction types",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated asset symbols",
                        "name": "assets",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated account names",
                        "name": "accounts",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated tag names",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Counterparty name",
                        "name": "counterparty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Transaction"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Get a list of transactions or create a new one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List or create transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated transaction types",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated asset symbols",
                        "name": "assets",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated account names",
                        "name": "accounts",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated tag names",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Counterparty name",
                        "name": "counterparty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Transaction"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "description": "Operate on a single transaction by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get, update, or delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Operate on a single transaction by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get, update, or delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Operate on a single transaction by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get, update, or delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_tropicaldog17_nami_internal_models.AccountPnL": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "realized_pnl_usd": {
                    "type": "number"
                },
                "realized_pnl_vnd": {
                    "type": "number"
                },
                "total_pnl_usd": {
                    "type": "number"
                },
                "total_pnl_vnd": {
                    "type": "number"
                },
                "total_value_usd": {
                    "type": "number"
                },
                "total_value_vnd": {
                    "type": "number"
                },
                "unrealized_pnl_usd": {
                    "type": "number"
                },
                "unrealized_pnl_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.ActionRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.ActionResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "executed_at": {
                    "type": "string"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Transaction"
                    }
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.AssetPnL": {
            "type": "object",
            "properties": {
                "asset": {
                    "type": "string"
                },
                "average_cost_usd": {
                    "type": "number"
                },
                "current_quantity": {
                    "type": "number"
                },
                "current_value_usd": {
                    "type": "number"
                },
                "current_value_vnd": {
                    "type": "number"
                },
                "realized_pnl_usd": {
                    "type": "number"
                },
                "realized_pnl_vnd": {
                    "type": "number"
                },
                "total_pnl_usd": {
                    "type": "number"
                },
                "total_pnl_vnd": {
                    "type": "number"
                },
                "unrealized_pnl_usd": {
                    "type": "number"
                },
                "unrealized_pnl_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.CashFlowByType": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "inflow_usd": {
                    "type": "number"
                },
                "inflow_vnd": {
                    "type": "number"
                },
                "net_usd": {
                    "type": "number"
                },
                "net_vnd": {
                    "type": "number"
                },
                "outflow_usd": {
                    "type": "number"
                },
                "outflow_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.CashFlowReport": {
            "type": "object",
            "properties": {
                "by_tag": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.CashFlowByType"
                    }
                },
                "by_type": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.CashFlowByType"
                    }
                },
                "net_usd": {
                    "type": "number"
                },
                "net_vnd": {
                    "type": "number"
                },
                "period": {
                    "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Period"
                },
                "total_in_usd": {
                    "type": "number"
                },
                "total_in_vnd": {
                    "type": "number"
                },
                "total_out_usd": {
                    "type": "number"
                },
                "total_out_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.Holding": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "asset": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "value_usd": {
                    "type": "number"
                },
                "value_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.HoldingSummary": {
            "type": "object",
            "properties": {
                "by_account": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Holding"
                        }
                    }
                },
                "by_asset": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Holding"
                    }
                },
                "last_updated": {
                    "type": "string"
                },
                "total_value_usd": {
                    "type": "number"
                },
                "total_value_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.OutstandingBorrow": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.Period": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.PnLReport": {
            "type": "object",
            "properties": {
                "by_account": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.AccountPnL"
                    }
                },
                "by_asset": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.AssetPnL"
                    }
                },
                "period": {
                    "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Period"
                },
                "realized_pnl_usd": {
                    "type": "number"
                },
                "realized_pnl_vnd": {
                    "type": "number"
                },
                "roi_percent": {
                    "type": "number"
                },
                "total_pnl_usd": {
                    "type": "number"
                },
                "total_pnl_vnd": {
                    "type": "number"
                },
                "unrealized_pnl_usd": {
                    "type": "number"
                },
                "unrealized_pnl_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.SpendingByTag": {
            "type": "object",
            "properties": {
                "amount_usd": {
                    "type": "number"
                },
                "amount_vnd": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.SpendingReport": {
            "type": "object",
            "properties": {
                "by_counterparty": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.SpendingByTag"
                    }
                },
                "by_tag": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.SpendingByTag"
                    }
                },
                "period": {
                    "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.Period"
                },
                "top_expenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tropicaldog17_nami_internal_models.TransactionSummary"
                    }
                },
                "total_usd": {
                    "type": "number"
                },
                "total_vnd": {
                    "type": "number"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.Transaction": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount_local": {
                    "type": "number"
                },
                "amount_usd": {
                    "type": "number"
                },
                "amount_vnd": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "cashflow_usd": {
                    "type": "number"
                },
                "cashflow_vnd": {
                    "type": "number"
                },
                "counterparty": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "delta_qty": {
                    "description": "Derived metrics",
                    "type": "number"
                },
                "entry_date": {
                    "type": "string"
                },
                "exit_date": {
                    "type": "string"
                },
                "fee_usd": {
                    "description": "Fees",
                    "type": "number"
                },
                "fee_vnd": {
                    "type": "number"
                },
                "fx_impact": {
                    "type": "number"
                },
                "fx_source": {
                    "description": "Audit fields",
                    "type": "string"
                },
                "fx_timestamp": {
                    "type": "string"
                },
                "fx_to_usd": {
                    "description": "FX and dual currency",
                    "type": "number"
                },
                "fx_to_vnd": {
                    "type": "number"
                },
                "horizon": {
                    "description": "Optional tracking",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "price_local": {
                    "type": "number"
                },
                "quantity": {
                    "description": "Amount fields",
                    "type": "number"
                },
                "tag": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_tropicaldog17_nami_internal_models.TransactionSummary": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount_usd": {
                    "type": "number"
                },
                "amount_vnd": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "counterparty": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Nami Backend API",
	Description:      "API documentation for Nami Transaction Tracking System.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
